// <auto-generated />
using System;
using HRMS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRMS.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181206091337_V1.0.4")]
    partial class V104
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRMS.Database.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckClass")
                        .HasMaxLength(4);

                    b.Property<DateTime>("CheckTime");

                    b.Property<string>("CheckType")
                        .HasMaxLength(4);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("HRMS.Database.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Attachment")
                        .HasMaxLength(500);

                    b.Property<string>("Contact")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("CreditCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("Establishment");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(20);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("OperationPeriod")
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<string>("RegisteredAddress")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("RegisteredCapital")
                        .HasMaxLength(20);

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.Property<string>("Representative")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool>("Valid");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("HRMS.Database.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlertDays");

                    b.Property<string>("Attachment")
                        .HasMaxLength(500);

                    b.Property<string>("Contents")
                        .HasMaxLength(500);

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Contractor")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Department")
                        .HasMaxLength(150);

                    b.Property<DateTime>("InvalidDate");

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.Property<string>("Owner")
                        .HasMaxLength(150);

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.Property<string>("Status")
                        .HasMaxLength(4);

                    b.Property<DateTime>("ValidDate");

                    b.HasKey("Id");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("HRMS.Database.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.Property<bool>("Valid");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("HRMS.Database.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachment")
                        .HasMaxLength(500);

                    b.Property<DateTime>("Birth");

                    b.Property<DateTime?>("CertificateDate");

                    b.Property<string>("Certificates")
                        .HasMaxLength(200);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime?>("DimissionDate");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("EmContactPhone")
                        .HasMaxLength(20);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(20);

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeStatus")
                        .HasMaxLength(4);

                    b.Property<string>("EmployeeType")
                        .HasMaxLength(4);

                    b.Property<DateTime?>("EntryDate");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("GraduateFrom")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("GraduationDate");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("IdentityType")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("LabourCompany")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Marital")
                        .HasMaxLength(4);

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<string>("Political")
                        .HasMaxLength(20);

                    b.Property<string>("Position");

                    b.Property<string>("RegisteredResidence")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.Property<string>("Residence")
                        .HasMaxLength(200);

                    b.Property<string>("TermOfContract")
                        .HasMaxLength(10);

                    b.Property<bool>("Valid");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("HRMS.Database.Entities.EmployeeDimissionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150);

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("DimmissionTime");

                    b.Property<string>("DimmissionType");

                    b.Property<DateTime?>("EffectiveDate");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("LabourCompany")
                        .HasMaxLength(150);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Position")
                        .HasMaxLength(150);

                    b.Property<string>("Reason")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("EmployeeDimission");
                });

            modelBuilder.Entity("HRMS.Database.Entities.EmployeeEntryInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150);

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime?>("EffectiveDate");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(150);

                    b.Property<DateTime>("EntryTime");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("LabourCompany")
                        .HasMaxLength(150);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Position")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("EmployeeEntry");
                });

            modelBuilder.Entity("HRMS.Database.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Control")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int?>("OrderIndex");

                    b.Property<int?>("ParentID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("HRMS.Database.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int>("DepartmentId");

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<bool>("Valid");

                    b.HasKey("Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("HRMS.Database.Entities.PositionTransferCrossDepart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BackTime");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("DepartmentIn")
                        .HasMaxLength(150);

                    b.Property<string>("DepartmentOut")
                        .HasMaxLength(150);

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(150);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("OnTheWay")
                        .HasMaxLength(10);

                    b.Property<string>("PositionIn")
                        .HasMaxLength(150);

                    b.Property<string>("PositionOut")
                        .HasMaxLength(150);

                    b.Property<DateTime>("TransferOutTime");

                    b.Property<string>("TransferedInBy")
                        .HasMaxLength(150);

                    b.Property<string>("TransferedOutBy")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("TransferCrossDepart");
                });

            modelBuilder.Entity("HRMS.Database.Entities.PositionTransferInnerDepart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("PositionIn")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("PositionOut")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("TransferTime");

                    b.Property<string>("TransferType")
                        .HasMaxLength(4);

                    b.Property<string>("TransferedBy")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("TransferInnerDepart");
                });

            modelBuilder.Entity("HRMS.Database.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("HRMS.Database.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<int>("PermissionId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("HRMS.Database.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Attachment")
                        .HasMaxLength(500);

                    b.Property<string>("BusinessType")
                        .HasMaxLength(4);

                    b.Property<string>("Contact")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("CreditCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<decimal>("Deposit");

                    b.Property<DateTime>("Establishment");

                    b.Property<bool>("IsLabour");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(20);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("OperationPeriod")
                        .HasMaxLength(10);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<string>("RegisteredAddress")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("RegisteredCapital")
                        .HasMaxLength(20);

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.Property<string>("Representative")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool>("Valid");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("HRMS.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AliasName")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsDisabled");

                    b.Property<DateTime?>("LastLoginDatetime");

                    b.Property<string>("LoginName")
                        .HasMaxLength(150);

                    b.Property<int?>("LoginNumber");

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Password")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HRMS.Database.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creator")
                        .HasMaxLength(150);

                    b.Property<string>("Modifier")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500);

                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
